@startuml
title save/update model activity Diagram
(*) --> "before hook"
if "enable validation?" then
    --> [yes] "validate"
    if "validate error" then
        --> [YES] "throw ValidateException"
        --> "onError hook"
        --> (*)
    else
        --> [NO] "get api provider"
    Endif
else
--> [NO] "get api provider"
Endif
if "api provider is configure?" then
    --> [NO] "throw ConfigureApiException"
    --> "onError hook"
else
Endif
--> "prepare data for save"
--> "run save()/update()"
--> "await operation result"
if "Save/Update Success?" then
    --> [NO] "catch exception"
    --> "onError hook"
else
    --> [YES] "onSave hook"
Endif
--> "after hook"
-->(*)
@enduml
